import os
import data
import numpy as np
import time
start = time.process_time()
# data.ge_accuracy("aaabtest")
# data.read_accuracy("aaabtest")
# data.ge_accuracy("aabtest")
# data.read_accuracy("aabtest")
#data.ge_accuracy("aaaaaaaaaa")
#data.read_accuracy("aaaaaaaaaa")
W1 = np.ones((2, 100))
np.savetxt("W1.txt", W1)
W2 = np.ones((100, 3))
np.savetxt("W2.txt", W2)
#B = np.random.randn(100, 3)
#np.savetxt("B.txt", B)
# filename1 = "C:\\biyesheji\\data\\9fold\\mr0\\train.txt"
# filename2 = "C:\\biyesheji\\data\\9fold\\mr0\\test.txt"
# #两个%s放在一块写就会把两个字符串变成一个
# os.system('python C:\\Users\\Zheng\\PycharmProjects\\tf\\classifier.py %s %s' %(filename1, filename2))
#data.gettest()
#data.testingmr0()
#data.testingmr1()
#data.testingmr2()
#data.testingmr3()
#data.testingmr4()
#data.testingmr5()
#data.testingmr6()
#data.allmr3()
#data.testingmr3()
#data.testingmr4()
#data.del_file(3)
#data.clearmr2()
#data.clearmr3()
#data.readmr3()
#data.allmr4()
#data.testingmr4()
#data.readmr(0)
#data.allmr6()
#data.del_file(6)
#data.allmr4()
#data.del_file(4)
#data.clearmr(1)
#data.clearmr(1)
#data.testingmr4()
#data.clearmr(1)
#data.readmr(1)
#data.testingmr3_('C:\\biyesheji\\data')
#data.testingmr1_('C:\\test_gui\\biyesheji\\data')
#re = data.readmr_(2, 'C:\\test_gui\\biyesheji\\data')
#print(re)
# re_dict1 = data.readmr_(1, 'C:\\test_gui\\biyesheji\\data')
# re_dict2 = data.readmr_(2, 'C:\\test_gui\\biyesheji\\data')
# re_dict3 = data.readmr_(3, 'C:\\test_gui\\biyesheji\\data')
# re_dict4 = data.readmr_(4, 'C:\\test_gui\\biyesheji\\data')
# re_dict5 = data.readmr_(5, 'C:\\test_gui\\biyesheji\\data')
# re_dict6 = data.readmr_(6, 'C:\\test_gui\\biyesheji\\data')
# print(re_dict1)
# print(re_dict2)
# print(re_dict3)
# print(re_dict4)
# print(re_dict5)
elapsed = (time.process_time() - start)
print("Time used:", elapsed)

